from pokemon_damage_calculator.model.enums import PokemonType, TypeMatchup


def clean_name(name: str) -> str:
    return name.lower().replace("-", "").replace(" ", "")


TYPE_CHART = {
    PokemonType.Normal: {
        PokemonType.Fighting: TypeMatchup.SuperEffective,
        PokemonType.Ghost: TypeMatchup.Immune,
    },
    PokemonType.Fire: {
        PokemonType.Fire: TypeMatchup.NotEffective,
        PokemonType.Water: TypeMatchup.SuperEffective,
        PokemonType.Grass: TypeMatchup.NotEffective,
        PokemonType.Ice: TypeMatchup.NotEffective,
        PokemonType.Ground: TypeMatchup.SuperEffective,
        PokemonType.Bug: TypeMatchup.NotEffective,
        PokemonType.Rock: TypeMatchup.SuperEffective,
        PokemonType.Steel: TypeMatchup.NotEffective,
        PokemonType.Fairy: TypeMatchup.NotEffective,
    },
    PokemonType.Water: {
        PokemonType.Fire: TypeMatchup.NotEffective,
        PokemonType.Water: TypeMatchup.NotEffective,
        PokemonType.Grass: TypeMatchup.SuperEffective,
        PokemonType.Electric: TypeMatchup.SuperEffective,
        PokemonType.Ice: TypeMatchup.NotEffective,
        PokemonType.Steel: TypeMatchup.NotEffective,
    },
    PokemonType.Grass: {
        PokemonType.Fire: TypeMatchup.SuperEffective,
        PokemonType.Water: TypeMatchup.NotEffective,
        PokemonType.Grass: TypeMatchup.NotEffective,
        PokemonType.Electric: TypeMatchup.NotEffective,
        PokemonType.Ice: TypeMatchup.SuperEffective,
        PokemonType.Poison: TypeMatchup.SuperEffective,
        PokemonType.Ground: TypeMatchup.NotEffective,
        PokemonType.Flying: TypeMatchup.SuperEffective,
        PokemonType.Bug: TypeMatchup.SuperEffective,
    },
    PokemonType.Electric: {
        PokemonType.Electric: TypeMatchup.NotEffective,
        PokemonType.Ground: TypeMatchup.SuperEffective,
        PokemonType.Flying: TypeMatchup.NotEffective,
        PokemonType.Steel: TypeMatchup.NotEffective,
    },
    PokemonType.Ice: {
        PokemonType.Fire: TypeMatchup.SuperEffective,
        PokemonType.Ice: TypeMatchup.NotEffective,
        PokemonType.Fighting: TypeMatchup.SuperEffective,
        PokemonType.Steel: TypeMatchup.SuperEffective,
    },
    PokemonType.Fighting: {
        PokemonType.Flying: TypeMatchup.SuperEffective,
        PokemonType.Psychic: TypeMatchup.SuperEffective,
        PokemonType.Bug: TypeMatchup.NotEffective,
        PokemonType.Rock: TypeMatchup.NotEffective,
        PokemonType.Dark: TypeMatchup.NotEffective,
        PokemonType.Fairy: TypeMatchup.SuperEffective,
    },
    PokemonType.Poison: {
        PokemonType.Grass: TypeMatchup.NotEffective,
        PokemonType.Fighting: TypeMatchup.NotEffective,
        PokemonType.Poison: TypeMatchup.NotEffective,
        PokemonType.Ground: TypeMatchup.SuperEffective,
        PokemonType.Psychic: TypeMatchup.SuperEffective,
        PokemonType.Bug: TypeMatchup.NotEffective,
        PokemonType.Fairy: TypeMatchup.NotEffective,
    },
    PokemonType.Ground: {
        PokemonType.Water: TypeMatchup.SuperEffective,
        PokemonType.Grass: TypeMatchup.SuperEffective,
        PokemonType.Electric: TypeMatchup.Immune,
        PokemonType.Ice: TypeMatchup.SuperEffective,
        PokemonType.Poison: TypeMatchup.NotEffective,
        PokemonType.Rock: TypeMatchup.NotEffective,
    },
    PokemonType.Flying: {
        PokemonType.Grass: TypeMatchup.NotEffective,
        PokemonType.Electric: TypeMatchup.SuperEffective,
        PokemonType.Ice: TypeMatchup.SuperEffective,
        PokemonType.Fighting: TypeMatchup.NotEffective,
        PokemonType.Ground: TypeMatchup.Immune,
        PokemonType.Bug: TypeMatchup.NotEffective,
        PokemonType.Rock: TypeMatchup.SuperEffective,
    },
    PokemonType.Psychic: {
        PokemonType.Fighting: TypeMatchup.NotEffective,
        PokemonType.Psychic: TypeMatchup.NotEffective,
        PokemonType.Bug: TypeMatchup.SuperEffective,
        PokemonType.Ghost: TypeMatchup.SuperEffective,
        PokemonType.Dark: TypeMatchup.SuperEffective,
    },
    PokemonType.Bug: {
        PokemonType.Fire: TypeMatchup.SuperEffective,
        PokemonType.Grass: TypeMatchup.NotEffective,
        PokemonType.Fighting: TypeMatchup.NotEffective,
        PokemonType.Ground: TypeMatchup.NotEffective,
        PokemonType.Flying: TypeMatchup.SuperEffective,
        PokemonType.Rock: TypeMatchup.SuperEffective,
    },
    PokemonType.Rock: {
        PokemonType.Normal: TypeMatchup.NotEffective,
        PokemonType.Fire: TypeMatchup.NotEffective,
        PokemonType.Water: TypeMatchup.SuperEffective,
        PokemonType.Grass: TypeMatchup.SuperEffective,
        PokemonType.Fighting: TypeMatchup.SuperEffective,
        PokemonType.Poison: TypeMatchup.NotEffective,
        PokemonType.Ground: TypeMatchup.SuperEffective,
        PokemonType.Flying: TypeMatchup.NotEffective,
        PokemonType.Steel: TypeMatchup.SuperEffective,
    },
    PokemonType.Ghost: {
        PokemonType.Normal: TypeMatchup.Immune,
        PokemonType.Fighting: TypeMatchup.Immune,
        PokemonType.Poison: TypeMatchup.NotEffective,
        PokemonType.Bug: TypeMatchup.NotEffective,
        PokemonType.Ghost: TypeMatchup.SuperEffective,
        PokemonType.Dark: TypeMatchup.SuperEffective,
    },
    PokemonType.Dragon: {
        PokemonType.Fire: TypeMatchup.NotEffective,
        PokemonType.Water: TypeMatchup.NotEffective,
        PokemonType.Grass: TypeMatchup.NotEffective,
        PokemonType.Electric: TypeMatchup.NotEffective,
        PokemonType.Ice: TypeMatchup.SuperEffective,
        PokemonType.Dragon: TypeMatchup.SuperEffective,
        PokemonType.Fairy: TypeMatchup.SuperEffective,
    },
    PokemonType.Dark: {
        PokemonType.Fighting: TypeMatchup.SuperEffective,
        PokemonType.Psychic: TypeMatchup.Immune,
        PokemonType.Bug: TypeMatchup.SuperEffective,
        PokemonType.Ghost: TypeMatchup.NotEffective,
        PokemonType.Dark: TypeMatchup.NotEffective,
        PokemonType.Fairy: TypeMatchup.SuperEffective,
    },
    PokemonType.Steel: {
        PokemonType.Normal: TypeMatchup.NotEffective,
        PokemonType.Fire: TypeMatchup.SuperEffective,
        PokemonType.Grass: TypeMatchup.NotEffective,
        PokemonType.Ice: TypeMatchup.NotEffective,
        PokemonType.Fighting: TypeMatchup.SuperEffective,
        PokemonType.Poison: TypeMatchup.Immune,
        PokemonType.Ground: TypeMatchup.SuperEffective,
        PokemonType.Flying: TypeMatchup.NotEffective,
        PokemonType.Psychic: TypeMatchup.NotEffective,
        PokemonType.Bug: TypeMatchup.NotEffective,
        PokemonType.Rock: TypeMatchup.NotEffective,
        PokemonType.Dragon: TypeMatchup.NotEffective,
        PokemonType.Steel: TypeMatchup.NotEffective,
        PokemonType.Fairy: TypeMatchup.NotEffective,
    },
    PokemonType.Fairy: {
        PokemonType.Fighting: TypeMatchup.NotEffective,
        PokemonType.Poison: TypeMatchup.SuperEffective,
        PokemonType.Bug: TypeMatchup.NotEffective,
        PokemonType.Dragon: TypeMatchup.Immune,
        PokemonType.Dark: TypeMatchup.NotEffective,
        PokemonType.Steel: TypeMatchup.SuperEffective,
    },
    PokemonType.Unknown: {},
    PokemonType.Bird: {},
}
