from enum import Enum

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    pass


class BoostableStat(Enum):
    HP = "hp"
    Attack = "atk"
    Defence = "def"
    SpecialAttack = "spa"
    SpecialDefence = "spd"
    Speed = "spe"
    Accuracy = "accuracy"
    Evasopn = "evasion"


class Stat(Enum):
    HP = "hp"
    Attack = "atk"
    Defence = "def"
    SpecialAttack = "spa"
    SpecialDefence = "spd"
    Speed = "spe"


class Ability(Enum):
    NoAbility = ""
    Adaptability = "Adaptability"
    Aerilate = "Aerilate"
    Aftermath = "Aftermath"
    AirLock = "Air Lock"
    Analytic = "Analytic"
    AngerPoint = "Anger Point"
    AngerShell = "Anger Shell"
    Anticipation = "Anticipation"
    ArenaTrap = "Arena Trap"
    ArmorTail = "Armor Tail"
    AromaVeil = "Aroma Veil"
    AsOneGlastrier = "As One (Glastrier)"
    AsOneSpectrier = "As One (Spectrier)"
    AuraBreak = "Aura Break"
    BadDreams = "Bad Dreams"
    BallFetch = "Ball Fetch"
    Battery = "Battery"
    BattleArmor = "Battle Armor"
    BattleBond = "Battle Bond"
    BeadsofRuin = "Beads of Ruin"
    BeastBoost = "Beast Boost"
    Berserk = "Berserk"
    BigPecks = "Big Pecks"
    Blaze = "Blaze"
    Bulletproof = "Bulletproof"
    CheekPouch = "Cheek Pouch"
    ChillingNeigh = "Chilling Neigh"
    Chlorophyll = "Chlorophyll"
    ClearBody = "Clear Body"
    CloudNine = "Cloud Nine"
    ColorChange = "Color Change"
    Comatose = "Comatose"
    Commander = "Commander"
    Competitive = "Competitive"
    CompoundEyes = "Compound Eyes"
    Contrary = "Contrary"
    Corrosion = "Corrosion"
    Costar = "Costar"
    CottonDown = "Cotton Down"
    CudChew = "Cud Chew"
    CuriousMedicine = "Curious Medicine"
    CursedBody = "Cursed Body"
    CuteCharm = "Cute Charm"
    Damp = "Damp"
    Dancer = "Dancer"
    DarkAura = "Dark Aura"
    DauntlessShield = "Dauntless Shield"
    Dazzling = "Dazzling"
    Defeatist = "Defeatist"
    Defiant = "Defiant"
    DeltaStream = "Delta Stream"
    DesolateLand = "Desolate Land"
    Disguise = "Disguise"
    Download = "Download"
    DragonsMaw = "Dragon's Maw"
    Drizzle = "Drizzle"
    Drought = "Drought"
    DrySkin = "Dry Skin"
    EarlyBird = "Early Bird"
    EarthEater = "Earth Eater"
    EffectSpore = "Effect Spore"
    ElectricSurge = "Electric Surge"
    Electromorphosis = "Electromorphosis"
    EmbodyAspectCornerstone = "Embody Aspect (Cornerstone)"
    EmbodyAspectHearthflame = "Embody Aspect (Hearthflame)"
    EmbodyAspectTeal = "Embody Aspect (Teal)"
    EmbodyAspectWellspring = "Embody Aspect (Wellspring)"
    EmergencyExit = "Emergency Exit"
    FairyAura = "Fairy Aura"
    Filter = "Filter"
    FlameBody = "Flame Body"
    FlareBoost = "Flare Boost"
    FlashFire = "Flash Fire"
    FlowerGift = "Flower Gift"
    FlowerVeil = "Flower Veil"
    Fluffy = "Fluffy"
    Forecast = "Forecast"
    Forewarn = "Forewarn"
    FriendGuard = "Friend Guard"
    Frisk = "Frisk"
    FullMetalBody = "Full Metal Body"
    FurCoat = "Fur Coat"
    GaleWings = "Gale Wings"
    Galvanize = "Galvanize"
    Gluttony = "Gluttony"
    GoodasGold = "Good as Gold"
    Gooey = "Gooey"
    GorillaTactics = "Gorilla Tactics"
    GrassPelt = "Grass Pelt"
    GrassySurge = "Grassy Surge"
    GrimNeigh = "Grim Neigh"
    GuardDog = "Guard Dog"
    GulpMissile = "Gulp Missile"
    Guts = "Guts"
    HadronEngine = "Hadron Engine"
    Harvest = "Harvest"
    Healer = "Healer"
    Heatproof = "Heatproof"
    HeavyMetal = "Heavy Metal"
    HoneyGather = "Honey Gather"
    Hospitality = "Hospitality"
    HugePower = "Huge Power"
    HungerSwitch = "Hunger Switch"
    Hustle = "Hustle"
    Hydration = "Hydration"
    HyperCutter = "Hyper Cutter"
    IceBody = "Ice Body"
    IceFace = "Ice Face"
    IceScales = "Ice Scales"
    Illuminate = "Illuminate"
    Illusion = "Illusion"
    Immunity = "Immunity"
    Imposter = "Imposter"
    Infiltrator = "Infiltrator"
    InnardsOut = "Innards Out"
    InnerFocus = "Inner Focus"
    Insomnia = "Insomnia"
    Intimidate = "Intimidate"
    IntrepidSword = "Intrepid Sword"
    IronBarbs = "Iron Barbs"
    IronFist = "Iron Fist"
    Justified = "Justified"
    KeenEye = "Keen Eye"
    Klutz = "Klutz"
    LeafGuard = "Leaf Guard"
    Levitate = "Levitate"
    Libero = "Libero"
    LightMetal = "Light Metal"
    LightningRod = "Lightning Rod"
    Limber = "Limber"
    LingeringAroma = "Lingering Aroma"
    LiquidOoze = "Liquid Ooze"
    LiquidVoice = "Liquid Voice"
    LongReach = "Long Reach"
    MagicBounce = "Magic Bounce"
    MagicGuard = "Magic Guard"
    Magician = "Magician"
    MagmaArmor = "Magma Armor"
    MagnetPull = "Magnet Pull"
    MarvelScale = "Marvel Scale"
    MegaLauncher = "Mega Launcher"
    Merciless = "Merciless"
    Mimicry = "Mimicry"
    MindsEye = "Mind's Eye"
    Minus = "Minus"
    MirrorArmor = "Mirror Armor"
    MistySurge = "Misty Surge"
    MoldBreaker = "Mold Breaker"
    Moody = "Moody"
    MotorDrive = "Motor Drive"
    Mountaineer = "Mountaineer"
    Moxie = "Moxie"
    Multiscale = "Multiscale"
    Multitype = "Multitype"
    Mummy = "Mummy"
    MyceliumMight = "Mycelium Might"
    NaturalCure = "Natural Cure"
    Neuroforce = "Neuroforce"
    NeutralizingGas = "Neutralizing Gas"
    NoGuard = "No Guard"
    Normalize = "Normalize"
    Oblivious = "Oblivious"
    Opportunist = "Opportunist"
    OrichalcumPulse = "Orichalcum Pulse"
    Overcoat = "Overcoat"
    Overgrow = "Overgrow"
    OwnTempo = "Own Tempo"
    ParentalBond = "Parental Bond"
    PastelVeil = "Pastel Veil"
    PerishBody = "Perish Body"
    Persistent = "Persistent"
    Pickpocket = "Pickpocket"
    Pickup = "Pickup"
    Pixilate = "Pixilate"
    Plus = "Plus"
    PoisonHeal = "Poison Heal"
    PoisonPoint = "Poison Point"
    PoisonPuppeteer = "Poison Puppeteer"
    PoisonTouch = "Poison Touch"
    PowerConstruct = "Power Construct"
    PowerSpot = "Power Spot"
    PowerofAlchemy = "Power of Alchemy"
    Prankster = "Prankster"
    Pressure = "Pressure"
    PrimordialSea = "Primordial Sea"
    PrismArmor = "Prism Armor"
    PropellerTail = "Propeller Tail"
    Protean = "Protean"
    Protosynthesis = "Protosynthesis"
    PsychicSurge = "Psychic Surge"
    PunkRock = "Punk Rock"
    PurePower = "Pure Power"
    PurifyingSalt = "Purifying Salt"
    QuarkDrive = "Quark Drive"
    QueenlyMajesty = "Queenly Majesty"
    QuickDraw = "Quick Draw"
    QuickFeet = "Quick Feet"
    RKSSystem = "RKS System"
    RainDish = "Rain Dish"
    Rattled = "Rattled"
    Rebound = "Rebound"
    Receiver = "Receiver"
    Reckless = "Reckless"
    Refrigerate = "Refrigerate"
    Regenerator = "Regenerator"
    Ripen = "Ripen"
    Rivalry = "Rivalry"
    RockHead = "Rock Head"
    RockyPayload = "Rocky Payload"
    RoughSkin = "Rough Skin"
    RunAway = "Run Away"
    SandForce = "Sand Force"
    SandRush = "Sand Rush"
    SandSpit = "Sand Spit"
    SandStream = "Sand Stream"
    SandVeil = "Sand Veil"
    SapSipper = "Sap Sipper"
    Schooling = "Schooling"
    Scrappy = "Scrappy"
    ScreenCleaner = "Screen Cleaner"
    SeedSower = "Seed Sower"
    SereneGrace = "Serene Grace"
    ShadowShield = "Shadow Shield"
    ShadowTag = "Shadow Tag"
    Sharpness = "Sharpness"
    ShedSkin = "Shed Skin"
    SheerForce = "Sheer Force"
    ShellArmor = "Shell Armor"
    ShieldDust = "Shield Dust"
    ShieldsDown = "Shields Down"
    Simple = "Simple"
    SkillLink = "Skill Link"
    SlowStart = "Slow Start"
    SlushRush = "Slush Rush"
    Sniper = "Sniper"
    SnowCloak = "Snow Cloak"
    SnowWarning = "Snow Warning"
    SolarPower = "Solar Power"
    SolidRock = "Solid Rock"
    SoulHeart = "Soul-Heart"
    Soundproof = "Soundproof"
    SpeedBoost = "Speed Boost"
    Stakeout = "Stakeout"
    Stall = "Stall"
    Stalwart = "Stalwart"
    Stamina = "Stamina"
    StanceChange = "Stance Change"
    Static = "Static"
    Steadfast = "Steadfast"
    SteamEngine = "Steam Engine"
    Steelworker = "Steelworker"
    SteelySpirit = "Steely Spirit"
    Stench = "Stench"
    StickyHold = "Sticky Hold"
    StormDrain = "Storm Drain"
    StrongJaw = "Strong Jaw"
    Sturdy = "Sturdy"
    SuctionCups = "Suction Cups"
    SuperLuck = "Super Luck"
    SupersweetSyrup = "Supersweet Syrup"
    SupremeOverlord = "Supreme Overlord"
    SurgeSurfer = "Surge Surfer"
    Swarm = "Swarm"
    SweetVeil = "Sweet Veil"
    SwiftSwim = "Swift Swim"
    SwordofRuin = "Sword of Ruin"
    Symbiosis = "Symbiosis"
    Synchronize = "Synchronize"
    TabletsofRuin = "Tablets of Ruin"
    TangledFeet = "Tangled Feet"
    TanglingHair = "Tangling Hair"
    Technician = "Technician"
    Telepathy = "Telepathy"
    TeraShell = "Tera Shell"
    TeraShift = "Tera Shift"
    TeraformZero = "Teraform Zero"
    Teravolt = "Teravolt"
    ThermalExchange = "Thermal Exchange"
    ThickFat = "Thick Fat"
    TintedLens = "Tinted Lens"
    Torrent = "Torrent"
    ToughClaws = "Tough Claws"
    ToxicBoost = "Toxic Boost"
    ToxicChain = "Toxic Chain"
    ToxicDebris = "Toxic Debris"
    Trace = "Trace"
    Transistor = "Transistor"
    Triage = "Triage"
    Truant = "Truant"
    Turboblaze = "Turboblaze"
    Unaware = "Unaware"
    Unburden = "Unburden"
    Unnerve = "Unnerve"
    UnseenFist = "Unseen Fist"
    VesselofRuin = "Vessel of Ruin"
    VictoryStar = "Victory Star"
    VitalSpirit = "Vital Spirit"
    VoltAbsorb = "Volt Absorb"
    WanderingSpirit = "Wandering Spirit"
    WaterAbsorb = "Water Absorb"
    WaterBubble = "Water Bubble"
    WaterCompaction = "Water Compaction"
    WaterVeil = "Water Veil"
    WeakArmor = "Weak Armor"
    WellBakedBody = "Well-Baked Body"
    WhiteSmoke = "White Smoke"
    WimpOut = "Wimp Out"
    WindPower = "Wind Power"
    WindRider = "Wind Rider"
    WonderGuard = "Wonder Guard"
    WonderSkin = "Wonder Skin"
    ZenMode = "Zen Mode"
    ZerotoHero = "Zero to Hero"


class MoveCategory(Enum):
    Physical = "Physical"
    Special = "Special"
    Status = "Status"


class MoveFlag(Enum):
    Recharge = "recharge"
    Protect = "protect"
    Pulse = "pulse"
    NoSketch = "nosketch"
    CantUseTwice = "cantusetwice"
    Gravity = "gravity"
    NonSky = "nonsky"
    Snatch = "snatch"
    Sound = "sound"
    AllyAnim = "allyanim"
    Punch = "punch"
    NoParentalBond = "noparentalbond"
    NoAssist = "noassist"
    Contact = "contact"
    PledgeCombo = "pledgecombo"
    Wind = "wind"
    Charge = "charge"
    Defrost = "defrost"
    MustPressure = "mustpressure"
    FailMeFirst = "failmefirst"
    FailMimic = "failmimic"
    FailInstruct = "failinstruct"
    Distance = "distance"
    FutureMove = "futuremove"
    Slicing = "slicing"
    Bite = "bite"
    BypassSub = "bypasssub"
    Reflectable = "reflectable"
    NoSleepTalk = "nosleeptalk"
    FailCopycat = "failcopycat"
    Mirror = "mirror"
    Bullet = "bullet"
    Metronome = "metronome"
    Powder = "powder"
    Heal = "heal"
    FailEncore = "failencore"
    Dance = "dance"


class IsNonStandard(Enum):
    LGPE = "LGPE"
    Past = "Past"
    CAP = "CAP"
    Gigantamax = "Gigantamax"
    Unobtainable = "Unobtainable"


class Target(Enum):
    AllySide = "allySide"
    AdjacentAlly = "adjacentAlly"
    FoeSide = "foeSide"
    AllAdjacent = "allAdjacent"
    Scripted = "scripted"
    All = "all"
    Normal = "normal"
    AllAdjacentFoes = "allAdjacentFoes"
    AdjacentAllyOrSelf = "adjacentAllyOrSelf"
    AllyTeam = "allyTeam"
    Self = "self"
    Any = "any"
    Allies = "allies"
    AdjacentFoe = "adjacentFoe"
    RandomNormal = "randomNormal"


class PokemonType(Enum):
    Normal = "Normal"
    Fire = "Fire"
    Water = "Water"
    Grass = "Grass"
    Flying = "Flying"
    Fighting = "Fighting"
    Poison = "Poison"
    Electric = "Electric"
    Ground = "Ground"
    Rock = "Rock"
    Psychic = "Psychic"
    Ice = "Ice"
    Bug = "Bug"
    Ghost = "Ghost"
    Steel = "Steel"
    Dragon = "Dragon"
    Dark = "Dark"
    Fairy = "Fairy"
    Bird = "Bird"
    Unknown = "???"


class ContestType(Enum):
    Clever = "Clever"
    Cute = "Cute"
    Tough = "Tough"
    Beautiful = "Beautiful"
    Cool = "Cool"


class VolatileStatus(Enum):
    Minimize = "minimize"
    HealBlock = "healblock"
    MiracleEye = "miracleeye"
    Torment = "torment"
    BanefulBunker = "banefulbunker"
    LaserFocus = "laserfocus"
    Grudge = "grudge"
    Bide = "bide"
    KingsShield = "kingsshield"
    Magnetrise = "magnetrise"
    Charge = "charge"
    Protect = "protect"
    MaxGuard = "maxguard"
    BurningBulwark = "burningbulwark"
    Curse = "curse"
    PartiallyTrapped = "partiallytrapped"
    Spotlight = "spotlight"
    Stockpile = "stockpile"
    Electrify = "electrify"
    Tarshot = "tarshot"
    Obstruct = "obstruct"
    Smackdown = "smackdown"
    FocusEnergy = "focusenergy"
    Foresight = "foresight"
    Disable = "disable"
    Confusion = "confusion"
    Snatch = "snatch"
    NoRetreat = "noretreat"
    Octolock = "octolock"
    DefenseCurl = "defensecurl"
    LeechSeed = "leechseed"
    MagicCoat = "magiccoat"
    Ingrain = "ingrain"
    DragonCheer = "dragoncheer"
    FollowMe = "followme"
    Nightmare = "nightmare"
    Taunt = "taunt"
    Telekinesis = "telekinesis"
    Endure = "endure"
    Attract = "attract"
    DestinyBond = "destinybond"
    Powder = "powder"
    Substitute = "substitute"
    AquaRing = "aquaring"
    SilkTrap = "silktrap"
    Imprison = "imprison"
    PowerShift = "powershift"
    PowerTrick = "powertrick"
    SpikyShield = "spikyshield"
    HelpingHand = "helpinghand"
    GastroAcid = "gastroacid"
    Embargo = "embargo"
    Encore = "encore"
    RagePowder = "ragepowder"
    Yawn = "yawn"


class SideCondition(Enum):
    Reflect = "reflect"
    Mist = "mist"
    ToxicSpikes = "toxicspikes"
    CraftyShield = "craftyshield"
    AuroraVeil = "auroraveil"
    MatBlock = "matblock"
    LuckyChant = "luckychant"
    SafeGuard = "safeguard"
    StickyWeb = "stickyweb"
    Spikes = "spikes"
    Tailwind = "tailwind"
    WideGuard = "wideguard"
    QuickGuard = "quickguard"
    StealthRock = "stealthrock"
    LightScreen = "lightscreen"


class UniqueSelfSwitch(Enum):
    BatonPass = "copyvolatile"
    ShedTail = "shedtail"


class Weather(Enum):
    NONE = None
    Sandstorm = "Sandstorm"
    SunnyDay = "sunnyday"
    RainDance = "RainDance"
    Snow = "snow"
    Hail = "hail"
    ExtremelyHarshSunlight = "extremelyharshsunlight"
    HeavyRain = "heavyrain"
    StrongWinds = "strongwinds"

    def difficult_to_override(self) -> bool:
        return self in [
            Weather.ExtremelyHarshSunlight,
            Weather.HeavyRain,
            Weather.StrongWinds,
        ]

    def type_multiplier(self, type_: PokemonType) -> float:
        match self:
            case Weather.SunnyDay | Weather.ExtremelyHarshSunlight if (
                type_ == PokemonType.Fire
            ):
                return 1.5
            case Weather.ExtremelyHarshSunlight if type_ == PokemonType.Water:
                return 0.0
            case Weather.SunnyDay if type_ == PokemonType.Water:
                return 0.5
            case Weather.RainDance if type_ == PokemonType.Fire:
                return 0.5
            case Weather.HeavyRain if type_ == PokemonType.Fire:
                return 0.0
            case Weather.RainDance | Weather.HeavyRain if type_ == PokemonType.Water:
                return 1.5
        return 1.0


class NonGhostTarget(Enum):
    Self = "self"


class Status(Enum):
    Toxic = "tox"
    Burn = "brn"
    Paralysis = "par"
    Sleep = "slp"
    Poison = "psn"


class UniqueDamage(Enum):
    Level = "level"


class Terrain(Enum):
    NONE = None
    Misty = "mistyterrain"
    Psychic = "psychicterrain"
    Grassy = "grassyterrain"
    Electric = "electricterrain"

    def type_multiplier(self, type_: PokemonType) -> float:
        match self:
            case Terrain.Psychic if type_ == PokemonType.Psychic:
                return 1.3
            case Terrain.Electric if type_ == PokemonType.Electric:
                return 1.3
            case Terrain.Grassy if type_ == PokemonType.Grass:
                return 1.3
        return 1.0


class MoveSelfDestructs(Enum):
    Always = "always"
    IfHit = "ifHit"


class PseudoWeather(Enum):
    IonDeluge = "iondeluge"
    MagicRoom = "magicroom"
    WaterSport = "watersport"
    FairyLock = "fairylock"
    WonderRoom = "wonderroom"
    TrickRoom = "trickroom"
    Gravity = "gravity"
    MudSport = "mudsport"


class UniqueOHKO(Enum):
    SheerCold = "Ice"


class UniqueOffensivePokemon(Enum):
    FoulPlay = "target"


class UniqueSlotCondition(Enum):
    HealingWish = "healingwish"
    LunarDance = "lunardance"
    RevivalBlessing = "revivalblessing"
    Wish = "Wish"


class TypeMatchup(float, Enum):
    Immune = 0
    NotEffective = 0.5
    Neutral = 1
    SuperEffective = 2
